<?php
/**
 * @author      Sergey Babko <srgbabko@gmail.com>
 * @copyright   © 2017 farior (https://github.com/farior)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var \Magento\Framework\View\TemplateEngine\Php $this */
/** @var \Farior\LayoutStructure\Block\Structure $block */

$jsonConfig = $block->renderStructureJsonConfig();
$rootConfig = reset($jsonConfig);
?>
<?php if ($rootConfig) : ?>
    <div class="chart dragscroll"
         id="layout-chart"
         data-mage-init='{"layoutChart": {
            "text": <?php echo json_encode($rootConfig['text']) ?>,
            "children": <?php echo json_encode($rootConfig['children']) ?>
         }}'>
    </div>
<?php endif; ?>
